name: ci

env:
  DENO_VERSION: 1.x

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Check fmt
        run: deno task fmt --check
      - name: Run lint
        run: deno task lint
      - name: Run type check
        run: deno task check