name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DENO_VERSION: 2.x

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Update dependencies
        run: |
          deno outdated --update &> ../output.txt
        env:
          NO_COLOR: 1
      - name: Read ../output.txt
        id: log
        uses: juliangruber/read-file-action@v1
        with:
          path: ../output.txt
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: Update Deno dependencies"
          title: "chore: Update Deno dependencies"
          body: |
            The output of `deno outdated --update` is

            ```
            ${{ steps.log.outputs.content }}
            ```
          branch: update-deno-dependencies
          delete-branch: true
          sign-commits: true
